### ISSUE TITLE
Spaces In Site Name Crash Installation

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/wpcr-website#3]
Specifying a value with spaces for `WPCR_SITE_TITLE` prompt, such as `"WP Code Reviews"` (even with quotes, like here) crashes the import with the following message:

> Error: Too many positional arguments: Code Reviews"

**Comment by mecha** [comment]
Definitely a must fix! Tested and reproduced the crash with "A name with spaces" (no quotes).

**Comment by XedinUnknown** [comment]
@mecha, please feel free to accept the PR when convenient.

**Comment by mecha** [comment]
Done! Closing the issue.
